### ISSUE TITLE
Can't get the rich tui to work

### ISSUE THREAD

**Issue by forslund** [OpenVoiceOS/ovos-cli-client#11]
The rich TUI only shows
```
Log Output:                                                          0-2 of 2
```

`--simple` does work as expected.

Maybe there is some old config file or a missing config file causing this?

**Comment by JarbasAl** [comment]
is this from github? i think pypi has a outdated version

**Comment by forslund** [comment]
I will verify.

**Comment by forslund** [comment]
Ah yes, installing from the repo seems to work!
